/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MusicCodec
{
  public enum BagExpandType
  {
    LEVEL_UP = 0,
    BUY = 1,
  }
}
