/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MusicCodec
{
  public enum GMPushType
  {
    VERSION_UPDATE = 1,
    ACTIVE_MESSAGE = 2,
    UPLOAD_PIC = 3,
    RECEIVE_GIFT = 4,
    OFFLINE_TIME = 5,
  }
}
