/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace MusicCodec
{
  public enum NumberType
  {
    COUPON = 0,
    IB = 1,
    FREE_IB = 2,
    EXP = 3,
    /// <summary>
    /// 人气值
    /// </summary>
    POP = 4,
    /// <summary>
    /// 通告币
    /// </summary>
    ANNOUNCE_IB = 5,
    /// <summary>
    /// 客户端初始化使用
    /// </summary>
    NONE = 1000,
  }
}
