/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace MusicCodec
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SlotDrawResult : TBase
  {
    private int _position;
    private int _diamondAmount;
    private int _bindDiamondAmount;

    public int Position
    {
      get
      {
        return _position;
      }
      set
      {
        __isset.position = true;
        this._position = value;
      }
    }

    public int DiamondAmount
    {
      get
      {
        return _diamondAmount;
      }
      set
      {
        __isset.diamondAmount = true;
        this._diamondAmount = value;
      }
    }

    public int BindDiamondAmount
    {
      get
      {
        return _bindDiamondAmount;
      }
      set
      {
        __isset.bindDiamondAmount = true;
        this._bindDiamondAmount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool position;
      public bool diamondAmount;
      public bool bindDiamondAmount;
    }

    public SlotDrawResult() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Position = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              DiamondAmount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              BindDiamondAmount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SlotDrawResult");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.position) {
        field.Name = "position";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Position);
        oprot.WriteFieldEnd();
      }
      if (__isset.diamondAmount) {
        field.Name = "diamondAmount";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DiamondAmount);
        oprot.WriteFieldEnd();
      }
      if (__isset.bindDiamondAmount) {
        field.Name = "bindDiamondAmount";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(BindDiamondAmount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SlotDrawResult(");
      sb.Append("Position: ");
      sb.Append(Position);
      sb.Append(",DiamondAmount: ");
      sb.Append(DiamondAmount);
      sb.Append(",BindDiamondAmount: ");
      sb.Append(BindDiamondAmount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
