/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace MusicCodec
{

  /// <summary>
  /// Ñ²ÑÝÐÇÊý½±Àø×´Ì¬ÐÅÏ¢
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TourStarPrizeStatus : TBase
  {
    private int _stars;
    private byte _getStatus;
    private MusicCodec.PrizeInfo _prizeInfos;

    public int Stars
    {
      get
      {
        return _stars;
      }
      set
      {
        __isset.stars = true;
        this._stars = value;
      }
    }

    public byte GetStatus
    {
      get
      {
        return _getStatus;
      }
      set
      {
        __isset.getStatus = true;
        this._getStatus = value;
      }
    }

    /// <summary>
    /// ½±Àø
    /// </summary>
    public MusicCodec.PrizeInfo PrizeInfos
    {
      get
      {
        return _prizeInfos;
      }
      set
      {
        __isset.prizeInfos = true;
        this._prizeInfos = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool stars;
      public bool getStatus;
      public bool prizeInfos;
    }

    public TourStarPrizeStatus() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Stars = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Byte) {
              GetStatus = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              PrizeInfos = new MusicCodec.PrizeInfo();
              PrizeInfos.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TourStarPrizeStatus");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.stars) {
        field.Name = "stars";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Stars);
        oprot.WriteFieldEnd();
      }
      if (__isset.getStatus) {
        field.Name = "getStatus";
        field.Type = TType.Byte;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(GetStatus);
        oprot.WriteFieldEnd();
      }
      if (PrizeInfos != null && __isset.prizeInfos) {
        field.Name = "prizeInfos";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        PrizeInfos.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TourStarPrizeStatus(");
      sb.Append("Stars: ");
      sb.Append(Stars);
      sb.Append(",GetStatus: ");
      sb.Append(GetStatus);
      sb.Append(",PrizeInfos: ");
      sb.Append(PrizeInfos== null ? "<null>" : PrizeInfos.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
