include "public.thrift"  
namespace csharp ThriftStruct

/**
 * Autogenerated by program
 *
 * Autho ZhuGeLongFei
 *
 * Do not edit unless you are sure that you know what you are doning
 */

struct Counter
{
	1:  i32   ID
	2:  i32   GameTimesIntCountID
	3:  i32   DailyIBGiftIntCountID
}
struct CounterArray
{
	1:list<Counter> valueList
}

