/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ling9527.music.common.msg.auto.sc;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 时尚栏信息
 */
public class SCFashionBagInfo implements org.apache.thrift.TBase<SCFashionBagInfo, SCFashionBagInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCFashionBagInfo");

  private static final org.apache.thrift.protocol.TField STYLE_FIELD_DESC = new org.apache.thrift.protocol.TField("style", org.apache.thrift.protocol.TType.BYTE, (short)1);
  private static final org.apache.thrift.protocol.TField FASHION_INFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("fashionInfos", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField CUR_USED_FASHION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("curUsedFashionId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCFashionBagInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCFashionBagInfoTupleSchemeFactory());
  }

  /**
   * 个性装扮类型
   */
  public byte style; // required
  /**
   * 该类型下所有时尚信息
   */
  public List<FashionInfo> fashionInfos; // required
  /**
   * 当前类型使用的时尚id
   */
  public int curUsedFashionId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 个性装扮类型
     */
    STYLE((short)1, "style"),
    /**
     * 该类型下所有时尚信息
     */
    FASHION_INFOS((short)2, "fashionInfos"),
    /**
     * 当前类型使用的时尚id
     */
    CUR_USED_FASHION_ID((short)3, "curUsedFashionId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STYLE
          return STYLE;
        case 2: // FASHION_INFOS
          return FASHION_INFOS;
        case 3: // CUR_USED_FASHION_ID
          return CUR_USED_FASHION_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STYLE_ISSET_ID = 0;
  private static final int __CURUSEDFASHIONID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.CUR_USED_FASHION_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STYLE, new org.apache.thrift.meta_data.FieldMetaData("style", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.FASHION_INFOS, new org.apache.thrift.meta_data.FieldMetaData("fashionInfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FashionInfo.class))));
    tmpMap.put(_Fields.CUR_USED_FASHION_ID, new org.apache.thrift.meta_data.FieldMetaData("curUsedFashionId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCFashionBagInfo.class, metaDataMap);
  }

  public SCFashionBagInfo() {
  }

  public SCFashionBagInfo(
    byte style,
    List<FashionInfo> fashionInfos)
  {
    this();
    this.style = style;
    setStyleIsSet(true);
    this.fashionInfos = fashionInfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCFashionBagInfo(SCFashionBagInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.style = other.style;
    if (other.isSetFashionInfos()) {
      List<FashionInfo> __this__fashionInfos = new ArrayList<FashionInfo>();
      for (FashionInfo other_element : other.fashionInfos) {
        __this__fashionInfos.add(new FashionInfo(other_element));
      }
      this.fashionInfos = __this__fashionInfos;
    }
    this.curUsedFashionId = other.curUsedFashionId;
  }

  public SCFashionBagInfo deepCopy() {
    return new SCFashionBagInfo(this);
  }

  @Override
  public void clear() {
    setStyleIsSet(false);
    this.style = 0;
    this.fashionInfos = null;
    setCurUsedFashionIdIsSet(false);
    this.curUsedFashionId = 0;
  }

  /**
   * 个性装扮类型
   */
  public byte getStyle() {
    return this.style;
  }

  /**
   * 个性装扮类型
   */
  public SCFashionBagInfo setStyle(byte style) {
    this.style = style;
    setStyleIsSet(true);
    return this;
  }

  public void unsetStyle() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STYLE_ISSET_ID);
  }

  /** Returns true if field style is set (has been assigned a value) and false otherwise */
  public boolean isSetStyle() {
    return EncodingUtils.testBit(__isset_bitfield, __STYLE_ISSET_ID);
  }

  public void setStyleIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STYLE_ISSET_ID, value);
  }

  public int getFashionInfosSize() {
    return (this.fashionInfos == null) ? 0 : this.fashionInfos.size();
  }

  public java.util.Iterator<FashionInfo> getFashionInfosIterator() {
    return (this.fashionInfos == null) ? null : this.fashionInfos.iterator();
  }

  public void addToFashionInfos(FashionInfo elem) {
    if (this.fashionInfos == null) {
      this.fashionInfos = new ArrayList<FashionInfo>();
    }
    this.fashionInfos.add(elem);
  }

  /**
   * 该类型下所有时尚信息
   */
  public List<FashionInfo> getFashionInfos() {
    return this.fashionInfos;
  }

  /**
   * 该类型下所有时尚信息
   */
  public SCFashionBagInfo setFashionInfos(List<FashionInfo> fashionInfos) {
    this.fashionInfos = fashionInfos;
    return this;
  }

  public void unsetFashionInfos() {
    this.fashionInfos = null;
  }

  /** Returns true if field fashionInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetFashionInfos() {
    return this.fashionInfos != null;
  }

  public void setFashionInfosIsSet(boolean value) {
    if (!value) {
      this.fashionInfos = null;
    }
  }

  /**
   * 当前类型使用的时尚id
   */
  public int getCurUsedFashionId() {
    return this.curUsedFashionId;
  }

  /**
   * 当前类型使用的时尚id
   */
  public SCFashionBagInfo setCurUsedFashionId(int curUsedFashionId) {
    this.curUsedFashionId = curUsedFashionId;
    setCurUsedFashionIdIsSet(true);
    return this;
  }

  public void unsetCurUsedFashionId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CURUSEDFASHIONID_ISSET_ID);
  }

  /** Returns true if field curUsedFashionId is set (has been assigned a value) and false otherwise */
  public boolean isSetCurUsedFashionId() {
    return EncodingUtils.testBit(__isset_bitfield, __CURUSEDFASHIONID_ISSET_ID);
  }

  public void setCurUsedFashionIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CURUSEDFASHIONID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STYLE:
      if (value == null) {
        unsetStyle();
      } else {
        setStyle((Byte)value);
      }
      break;

    case FASHION_INFOS:
      if (value == null) {
        unsetFashionInfos();
      } else {
        setFashionInfos((List<FashionInfo>)value);
      }
      break;

    case CUR_USED_FASHION_ID:
      if (value == null) {
        unsetCurUsedFashionId();
      } else {
        setCurUsedFashionId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STYLE:
      return Byte.valueOf(getStyle());

    case FASHION_INFOS:
      return getFashionInfos();

    case CUR_USED_FASHION_ID:
      return Integer.valueOf(getCurUsedFashionId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STYLE:
      return isSetStyle();
    case FASHION_INFOS:
      return isSetFashionInfos();
    case CUR_USED_FASHION_ID:
      return isSetCurUsedFashionId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCFashionBagInfo)
      return this.equals((SCFashionBagInfo)that);
    return false;
  }

  public boolean equals(SCFashionBagInfo that) {
    if (that == null)
      return false;

    boolean this_present_style = true;
    boolean that_present_style = true;
    if (this_present_style || that_present_style) {
      if (!(this_present_style && that_present_style))
        return false;
      if (this.style != that.style)
        return false;
    }

    boolean this_present_fashionInfos = true && this.isSetFashionInfos();
    boolean that_present_fashionInfos = true && that.isSetFashionInfos();
    if (this_present_fashionInfos || that_present_fashionInfos) {
      if (!(this_present_fashionInfos && that_present_fashionInfos))
        return false;
      if (!this.fashionInfos.equals(that.fashionInfos))
        return false;
    }

    boolean this_present_curUsedFashionId = true && this.isSetCurUsedFashionId();
    boolean that_present_curUsedFashionId = true && that.isSetCurUsedFashionId();
    if (this_present_curUsedFashionId || that_present_curUsedFashionId) {
      if (!(this_present_curUsedFashionId && that_present_curUsedFashionId))
        return false;
      if (this.curUsedFashionId != that.curUsedFashionId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(SCFashionBagInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SCFashionBagInfo typedOther = (SCFashionBagInfo)other;

    lastComparison = Boolean.valueOf(isSetStyle()).compareTo(typedOther.isSetStyle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStyle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.style, typedOther.style);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFashionInfos()).compareTo(typedOther.isSetFashionInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFashionInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fashionInfos, typedOther.fashionInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCurUsedFashionId()).compareTo(typedOther.isSetCurUsedFashionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurUsedFashionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.curUsedFashionId, typedOther.curUsedFashionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCFashionBagInfo(");
    boolean first = true;

    sb.append("style:");
    sb.append(this.style);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fashionInfos:");
    if (this.fashionInfos == null) {
      sb.append("null");
    } else {
      sb.append(this.fashionInfos);
    }
    first = false;
    if (isSetCurUsedFashionId()) {
      if (!first) sb.append(", ");
      sb.append("curUsedFashionId:");
      sb.append(this.curUsedFashionId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCFashionBagInfoStandardSchemeFactory implements SchemeFactory {
    public SCFashionBagInfoStandardScheme getScheme() {
      return new SCFashionBagInfoStandardScheme();
    }
  }

  private static class SCFashionBagInfoStandardScheme extends StandardScheme<SCFashionBagInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCFashionBagInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STYLE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.style = iprot.readByte();
              struct.setStyleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FASHION_INFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.fashionInfos = new ArrayList<FashionInfo>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  FashionInfo _elem2; // required
                  _elem2 = new FashionInfo();
                  _elem2.read(iprot);
                  struct.fashionInfos.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setFashionInfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CUR_USED_FASHION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.curUsedFashionId = iprot.readI32();
              struct.setCurUsedFashionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCFashionBagInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(STYLE_FIELD_DESC);
      oprot.writeByte(struct.style);
      oprot.writeFieldEnd();
      if (struct.fashionInfos != null) {
        oprot.writeFieldBegin(FASHION_INFOS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.fashionInfos.size()));
          for (FashionInfo _iter3 : struct.fashionInfos)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.isSetCurUsedFashionId()) {
        oprot.writeFieldBegin(CUR_USED_FASHION_ID_FIELD_DESC);
        oprot.writeI32(struct.curUsedFashionId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCFashionBagInfoTupleSchemeFactory implements SchemeFactory {
    public SCFashionBagInfoTupleScheme getScheme() {
      return new SCFashionBagInfoTupleScheme();
    }
  }

  private static class SCFashionBagInfoTupleScheme extends TupleScheme<SCFashionBagInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCFashionBagInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStyle()) {
        optionals.set(0);
      }
      if (struct.isSetFashionInfos()) {
        optionals.set(1);
      }
      if (struct.isSetCurUsedFashionId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetStyle()) {
        oprot.writeByte(struct.style);
      }
      if (struct.isSetFashionInfos()) {
        {
          oprot.writeI32(struct.fashionInfos.size());
          for (FashionInfo _iter4 : struct.fashionInfos)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetCurUsedFashionId()) {
        oprot.writeI32(struct.curUsedFashionId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCFashionBagInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.style = iprot.readByte();
        struct.setStyleIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.fashionInfos = new ArrayList<FashionInfo>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            FashionInfo _elem7; // required
            _elem7 = new FashionInfo();
            _elem7.read(iprot);
            struct.fashionInfos.add(_elem7);
          }
        }
        struct.setFashionInfosIsSet(true);
      }
      if (incoming.get(2)) {
        struct.curUsedFashionId = iprot.readI32();
        struct.setCurUsedFashionIdIsSet(true);
      }
    }
  }

}

