/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ling9527.music.common.msg.auto.sc;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SCGetTimingLotteryMsg implements org.apache.thrift.TBase<SCGetTimingLotteryMsg, SCGetTimingLotteryMsg._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SCGetTimingLotteryMsg");

  private static final org.apache.thrift.protocol.TField TIMING_LOTTERYS_FIELD_DESC = new org.apache.thrift.protocol.TField("timingLotterys", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SCGetTimingLotteryMsgStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SCGetTimingLotteryMsgTupleSchemeFactory());
  }

  public List<TimingLottery> timingLotterys; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMING_LOTTERYS((short)1, "timingLotterys");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMING_LOTTERYS
          return TIMING_LOTTERYS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMING_LOTTERYS, new org.apache.thrift.meta_data.FieldMetaData("timingLotterys", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TimingLottery.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SCGetTimingLotteryMsg.class, metaDataMap);
  }

  public SCGetTimingLotteryMsg() {
  }

  public SCGetTimingLotteryMsg(
    List<TimingLottery> timingLotterys)
  {
    this();
    this.timingLotterys = timingLotterys;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SCGetTimingLotteryMsg(SCGetTimingLotteryMsg other) {
    if (other.isSetTimingLotterys()) {
      List<TimingLottery> __this__timingLotterys = new ArrayList<TimingLottery>();
      for (TimingLottery other_element : other.timingLotterys) {
        __this__timingLotterys.add(new TimingLottery(other_element));
      }
      this.timingLotterys = __this__timingLotterys;
    }
  }

  public SCGetTimingLotteryMsg deepCopy() {
    return new SCGetTimingLotteryMsg(this);
  }

  @Override
  public void clear() {
    this.timingLotterys = null;
  }

  public int getTimingLotterysSize() {
    return (this.timingLotterys == null) ? 0 : this.timingLotterys.size();
  }

  public java.util.Iterator<TimingLottery> getTimingLotterysIterator() {
    return (this.timingLotterys == null) ? null : this.timingLotterys.iterator();
  }

  public void addToTimingLotterys(TimingLottery elem) {
    if (this.timingLotterys == null) {
      this.timingLotterys = new ArrayList<TimingLottery>();
    }
    this.timingLotterys.add(elem);
  }

  public List<TimingLottery> getTimingLotterys() {
    return this.timingLotterys;
  }

  public SCGetTimingLotteryMsg setTimingLotterys(List<TimingLottery> timingLotterys) {
    this.timingLotterys = timingLotterys;
    return this;
  }

  public void unsetTimingLotterys() {
    this.timingLotterys = null;
  }

  /** Returns true if field timingLotterys is set (has been assigned a value) and false otherwise */
  public boolean isSetTimingLotterys() {
    return this.timingLotterys != null;
  }

  public void setTimingLotterysIsSet(boolean value) {
    if (!value) {
      this.timingLotterys = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TIMING_LOTTERYS:
      if (value == null) {
        unsetTimingLotterys();
      } else {
        setTimingLotterys((List<TimingLottery>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMING_LOTTERYS:
      return getTimingLotterys();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TIMING_LOTTERYS:
      return isSetTimingLotterys();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SCGetTimingLotteryMsg)
      return this.equals((SCGetTimingLotteryMsg)that);
    return false;
  }

  public boolean equals(SCGetTimingLotteryMsg that) {
    if (that == null)
      return false;

    boolean this_present_timingLotterys = true && this.isSetTimingLotterys();
    boolean that_present_timingLotterys = true && that.isSetTimingLotterys();
    if (this_present_timingLotterys || that_present_timingLotterys) {
      if (!(this_present_timingLotterys && that_present_timingLotterys))
        return false;
      if (!this.timingLotterys.equals(that.timingLotterys))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(SCGetTimingLotteryMsg other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    SCGetTimingLotteryMsg typedOther = (SCGetTimingLotteryMsg)other;

    lastComparison = Boolean.valueOf(isSetTimingLotterys()).compareTo(typedOther.isSetTimingLotterys());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimingLotterys()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timingLotterys, typedOther.timingLotterys);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SCGetTimingLotteryMsg(");
    boolean first = true;

    sb.append("timingLotterys:");
    if (this.timingLotterys == null) {
      sb.append("null");
    } else {
      sb.append(this.timingLotterys);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SCGetTimingLotteryMsgStandardSchemeFactory implements SchemeFactory {
    public SCGetTimingLotteryMsgStandardScheme getScheme() {
      return new SCGetTimingLotteryMsgStandardScheme();
    }
  }

  private static class SCGetTimingLotteryMsgStandardScheme extends StandardScheme<SCGetTimingLotteryMsg> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SCGetTimingLotteryMsg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMING_LOTTERYS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list80 = iprot.readListBegin();
                struct.timingLotterys = new ArrayList<TimingLottery>(_list80.size);
                for (int _i81 = 0; _i81 < _list80.size; ++_i81)
                {
                  TimingLottery _elem82; // required
                  _elem82 = new TimingLottery();
                  _elem82.read(iprot);
                  struct.timingLotterys.add(_elem82);
                }
                iprot.readListEnd();
              }
              struct.setTimingLotterysIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SCGetTimingLotteryMsg struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.timingLotterys != null) {
        oprot.writeFieldBegin(TIMING_LOTTERYS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.timingLotterys.size()));
          for (TimingLottery _iter83 : struct.timingLotterys)
          {
            _iter83.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SCGetTimingLotteryMsgTupleSchemeFactory implements SchemeFactory {
    public SCGetTimingLotteryMsgTupleScheme getScheme() {
      return new SCGetTimingLotteryMsgTupleScheme();
    }
  }

  private static class SCGetTimingLotteryMsgTupleScheme extends TupleScheme<SCGetTimingLotteryMsg> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SCGetTimingLotteryMsg struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTimingLotterys()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTimingLotterys()) {
        {
          oprot.writeI32(struct.timingLotterys.size());
          for (TimingLottery _iter84 : struct.timingLotterys)
          {
            _iter84.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SCGetTimingLotteryMsg struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list85 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.timingLotterys = new ArrayList<TimingLottery>(_list85.size);
          for (int _i86 = 0; _i86 < _list85.size; ++_i86)
          {
            TimingLottery _elem87; // required
            _elem87 = new TimingLottery();
            _elem87.read(iprot);
            struct.timingLotterys.add(_elem87);
          }
        }
        struct.setTimingLotterysIsSet(true);
      }
    }
  }

}

