/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ling9527.music.common.msg.auto.sc;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 巡演章节信息
 */
public class TourChapterInfo implements org.apache.thrift.TBase<TourChapterInfo, TourChapterInfo._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TourChapterInfo");

  private static final org.apache.thrift.protocol.TField CHAPTER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("chapterId", org.apache.thrift.protocol.TType.I16, (short)1);
  private static final org.apache.thrift.protocol.TField ACTIVE_RAID_INFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("activeRaidInfos", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TourChapterInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TourChapterInfoTupleSchemeFactory());
  }

  /**
   * 章节id
   */
  public short chapterId; // required
  /**
   * 已激活关卡信息
   */
  public List<TourChapterRaidInfo> activeRaidInfos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 章节id
     */
    CHAPTER_ID((short)1, "chapterId"),
    /**
     * 已激活关卡信息
     */
    ACTIVE_RAID_INFOS((short)3, "activeRaidInfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CHAPTER_ID
          return CHAPTER_ID;
        case 3: // ACTIVE_RAID_INFOS
          return ACTIVE_RAID_INFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CHAPTERID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CHAPTER_ID, new org.apache.thrift.meta_data.FieldMetaData("chapterId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.ACTIVE_RAID_INFOS, new org.apache.thrift.meta_data.FieldMetaData("activeRaidInfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TourChapterRaidInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TourChapterInfo.class, metaDataMap);
  }

  public TourChapterInfo() {
  }

  public TourChapterInfo(
    short chapterId,
    List<TourChapterRaidInfo> activeRaidInfos)
  {
    this();
    this.chapterId = chapterId;
    setChapterIdIsSet(true);
    this.activeRaidInfos = activeRaidInfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TourChapterInfo(TourChapterInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.chapterId = other.chapterId;
    if (other.isSetActiveRaidInfos()) {
      List<TourChapterRaidInfo> __this__activeRaidInfos = new ArrayList<TourChapterRaidInfo>();
      for (TourChapterRaidInfo other_element : other.activeRaidInfos) {
        __this__activeRaidInfos.add(new TourChapterRaidInfo(other_element));
      }
      this.activeRaidInfos = __this__activeRaidInfos;
    }
  }

  public TourChapterInfo deepCopy() {
    return new TourChapterInfo(this);
  }

  @Override
  public void clear() {
    setChapterIdIsSet(false);
    this.chapterId = 0;
    this.activeRaidInfos = null;
  }

  /**
   * 章节id
   */
  public short getChapterId() {
    return this.chapterId;
  }

  /**
   * 章节id
   */
  public TourChapterInfo setChapterId(short chapterId) {
    this.chapterId = chapterId;
    setChapterIdIsSet(true);
    return this;
  }

  public void unsetChapterId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CHAPTERID_ISSET_ID);
  }

  /** Returns true if field chapterId is set (has been assigned a value) and false otherwise */
  public boolean isSetChapterId() {
    return EncodingUtils.testBit(__isset_bitfield, __CHAPTERID_ISSET_ID);
  }

  public void setChapterIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CHAPTERID_ISSET_ID, value);
  }

  public int getActiveRaidInfosSize() {
    return (this.activeRaidInfos == null) ? 0 : this.activeRaidInfos.size();
  }

  public java.util.Iterator<TourChapterRaidInfo> getActiveRaidInfosIterator() {
    return (this.activeRaidInfos == null) ? null : this.activeRaidInfos.iterator();
  }

  public void addToActiveRaidInfos(TourChapterRaidInfo elem) {
    if (this.activeRaidInfos == null) {
      this.activeRaidInfos = new ArrayList<TourChapterRaidInfo>();
    }
    this.activeRaidInfos.add(elem);
  }

  /**
   * 已激活关卡信息
   */
  public List<TourChapterRaidInfo> getActiveRaidInfos() {
    return this.activeRaidInfos;
  }

  /**
   * 已激活关卡信息
   */
  public TourChapterInfo setActiveRaidInfos(List<TourChapterRaidInfo> activeRaidInfos) {
    this.activeRaidInfos = activeRaidInfos;
    return this;
  }

  public void unsetActiveRaidInfos() {
    this.activeRaidInfos = null;
  }

  /** Returns true if field activeRaidInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetActiveRaidInfos() {
    return this.activeRaidInfos != null;
  }

  public void setActiveRaidInfosIsSet(boolean value) {
    if (!value) {
      this.activeRaidInfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CHAPTER_ID:
      if (value == null) {
        unsetChapterId();
      } else {
        setChapterId((Short)value);
      }
      break;

    case ACTIVE_RAID_INFOS:
      if (value == null) {
        unsetActiveRaidInfos();
      } else {
        setActiveRaidInfos((List<TourChapterRaidInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CHAPTER_ID:
      return Short.valueOf(getChapterId());

    case ACTIVE_RAID_INFOS:
      return getActiveRaidInfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CHAPTER_ID:
      return isSetChapterId();
    case ACTIVE_RAID_INFOS:
      return isSetActiveRaidInfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TourChapterInfo)
      return this.equals((TourChapterInfo)that);
    return false;
  }

  public boolean equals(TourChapterInfo that) {
    if (that == null)
      return false;

    boolean this_present_chapterId = true;
    boolean that_present_chapterId = true;
    if (this_present_chapterId || that_present_chapterId) {
      if (!(this_present_chapterId && that_present_chapterId))
        return false;
      if (this.chapterId != that.chapterId)
        return false;
    }

    boolean this_present_activeRaidInfos = true && this.isSetActiveRaidInfos();
    boolean that_present_activeRaidInfos = true && that.isSetActiveRaidInfos();
    if (this_present_activeRaidInfos || that_present_activeRaidInfos) {
      if (!(this_present_activeRaidInfos && that_present_activeRaidInfos))
        return false;
      if (!this.activeRaidInfos.equals(that.activeRaidInfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TourChapterInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TourChapterInfo typedOther = (TourChapterInfo)other;

    lastComparison = Boolean.valueOf(isSetChapterId()).compareTo(typedOther.isSetChapterId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChapterId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.chapterId, typedOther.chapterId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetActiveRaidInfos()).compareTo(typedOther.isSetActiveRaidInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActiveRaidInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.activeRaidInfos, typedOther.activeRaidInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TourChapterInfo(");
    boolean first = true;

    sb.append("chapterId:");
    sb.append(this.chapterId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("activeRaidInfos:");
    if (this.activeRaidInfos == null) {
      sb.append("null");
    } else {
      sb.append(this.activeRaidInfos);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TourChapterInfoStandardSchemeFactory implements SchemeFactory {
    public TourChapterInfoStandardScheme getScheme() {
      return new TourChapterInfoStandardScheme();
    }
  }

  private static class TourChapterInfoStandardScheme extends StandardScheme<TourChapterInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TourChapterInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CHAPTER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.chapterId = iprot.readI16();
              struct.setChapterIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ACTIVE_RAID_INFOS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.activeRaidInfos = new ArrayList<TourChapterRaidInfo>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  TourChapterRaidInfo _elem2; // required
                  _elem2 = new TourChapterRaidInfo();
                  _elem2.read(iprot);
                  struct.activeRaidInfos.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setActiveRaidInfosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TourChapterInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CHAPTER_ID_FIELD_DESC);
      oprot.writeI16(struct.chapterId);
      oprot.writeFieldEnd();
      if (struct.activeRaidInfos != null) {
        oprot.writeFieldBegin(ACTIVE_RAID_INFOS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.activeRaidInfos.size()));
          for (TourChapterRaidInfo _iter3 : struct.activeRaidInfos)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TourChapterInfoTupleSchemeFactory implements SchemeFactory {
    public TourChapterInfoTupleScheme getScheme() {
      return new TourChapterInfoTupleScheme();
    }
  }

  private static class TourChapterInfoTupleScheme extends TupleScheme<TourChapterInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TourChapterInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetChapterId()) {
        optionals.set(0);
      }
      if (struct.isSetActiveRaidInfos()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetChapterId()) {
        oprot.writeI16(struct.chapterId);
      }
      if (struct.isSetActiveRaidInfos()) {
        {
          oprot.writeI32(struct.activeRaidInfos.size());
          for (TourChapterRaidInfo _iter4 : struct.activeRaidInfos)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TourChapterInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.chapterId = iprot.readI16();
        struct.setChapterIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.activeRaidInfos = new ArrayList<TourChapterRaidInfo>(_list5.size);
          for (int _i6 = 0; _i6 < _list5.size; ++_i6)
          {
            TourChapterRaidInfo _elem7; // required
            _elem7 = new TourChapterRaidInfo();
            _elem7.read(iprot);
            struct.activeRaidInfos.add(_elem7);
          }
        }
        struct.setActiveRaidInfosIsSet(true);
      }
    }
  }

}

