/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ling9527.music.common.msg.auto.cs;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 领取成就奖励
 */
public class CSGetAchievePrize implements org.apache.thrift.TBase<CSGetAchievePrize, CSGetAchievePrize._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CSGetAchievePrize");

  private static final org.apache.thrift.protocol.TField ACHIEVE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("achieveId", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CSGetAchievePrizeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CSGetAchievePrizeTupleSchemeFactory());
  }

  /**
   * 成就id
   */
  public int achieveId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 成就id
     */
    ACHIEVE_ID((short)1, "achieveId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACHIEVE_ID
          return ACHIEVE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ACHIEVEID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACHIEVE_ID, new org.apache.thrift.meta_data.FieldMetaData("achieveId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CSGetAchievePrize.class, metaDataMap);
  }

  public CSGetAchievePrize() {
  }

  public CSGetAchievePrize(
    int achieveId)
  {
    this();
    this.achieveId = achieveId;
    setAchieveIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CSGetAchievePrize(CSGetAchievePrize other) {
    __isset_bitfield = other.__isset_bitfield;
    this.achieveId = other.achieveId;
  }

  public CSGetAchievePrize deepCopy() {
    return new CSGetAchievePrize(this);
  }

  @Override
  public void clear() {
    setAchieveIdIsSet(false);
    this.achieveId = 0;
  }

  /**
   * 成就id
   */
  public int getAchieveId() {
    return this.achieveId;
  }

  /**
   * 成就id
   */
  public CSGetAchievePrize setAchieveId(int achieveId) {
    this.achieveId = achieveId;
    setAchieveIdIsSet(true);
    return this;
  }

  public void unsetAchieveId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ACHIEVEID_ISSET_ID);
  }

  /** Returns true if field achieveId is set (has been assigned a value) and false otherwise */
  public boolean isSetAchieveId() {
    return EncodingUtils.testBit(__isset_bitfield, __ACHIEVEID_ISSET_ID);
  }

  public void setAchieveIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ACHIEVEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ACHIEVE_ID:
      if (value == null) {
        unsetAchieveId();
      } else {
        setAchieveId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ACHIEVE_ID:
      return Integer.valueOf(getAchieveId());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ACHIEVE_ID:
      return isSetAchieveId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CSGetAchievePrize)
      return this.equals((CSGetAchievePrize)that);
    return false;
  }

  public boolean equals(CSGetAchievePrize that) {
    if (that == null)
      return false;

    boolean this_present_achieveId = true;
    boolean that_present_achieveId = true;
    if (this_present_achieveId || that_present_achieveId) {
      if (!(this_present_achieveId && that_present_achieveId))
        return false;
      if (this.achieveId != that.achieveId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(CSGetAchievePrize other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    CSGetAchievePrize typedOther = (CSGetAchievePrize)other;

    lastComparison = Boolean.valueOf(isSetAchieveId()).compareTo(typedOther.isSetAchieveId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAchieveId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.achieveId, typedOther.achieveId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CSGetAchievePrize(");
    boolean first = true;

    sb.append("achieveId:");
    sb.append(this.achieveId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CSGetAchievePrizeStandardSchemeFactory implements SchemeFactory {
    public CSGetAchievePrizeStandardScheme getScheme() {
      return new CSGetAchievePrizeStandardScheme();
    }
  }

  private static class CSGetAchievePrizeStandardScheme extends StandardScheme<CSGetAchievePrize> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CSGetAchievePrize struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACHIEVE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.achieveId = iprot.readI32();
              struct.setAchieveIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CSGetAchievePrize struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ACHIEVE_ID_FIELD_DESC);
      oprot.writeI32(struct.achieveId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CSGetAchievePrizeTupleSchemeFactory implements SchemeFactory {
    public CSGetAchievePrizeTupleScheme getScheme() {
      return new CSGetAchievePrizeTupleScheme();
    }
  }

  private static class CSGetAchievePrizeTupleScheme extends TupleScheme<CSGetAchievePrize> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CSGetAchievePrize struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAchieveId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetAchieveId()) {
        oprot.writeI32(struct.achieveId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CSGetAchievePrize struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.achieveId = iprot.readI32();
        struct.setAchieveIdIsSet(true);
      }
    }
  }

}

